"use strict";

/**
 * Interface Game
 * Interface KeyPushListener
 * 
 * Purpose: 
 * Axis of change: Maze display needs
 * Axis of change: Display types
 *
 * Right now, mazeGames take their display and neural display. This is no good.
 * A mazeGame should provide its displayable objects when asked. Gluing them to 
 * a display should be something else's job. As for neural activity, it should
 * be generated by the mazeGame sending an event to subscribers.
 *
 * EventType
 *   # addSubscriber
 *   # removeSubscriber
 *   # trigger
 *   # getName
 *
 * Event
 *   # type
 *   # data 
 *
 * EventHandler
 *   # setBehavior(func)
 *   # trigger(event)
 */

MazeGame.MultiMaze = function () {

  var MultiMaze = function MultiMaze() {
    this.maze1;
    this.maze2;
    this.maze3;
  };

  return MultiMaze;
}();